    <select class="form-control" name="brand" id="make" required>
        <option value="">BRAND</option>
        <option value="Ambassador">Ambassador</option>
        <option value="BMW">BMW</option>
        <option value="Daewoo">Daewoo</option>
        <option value="Eicher">Eicher</option>
        <option value="Force">Force</option>
        <option value="FORD">Ford</option>
        <option value="Hero">Hero</option>
        <option value="Honda">Honda</option>
        <option value="Hyundai">Hyundai</option>
        <option value="Isuzu">Isuzu</option>
        <option value="Kia">Kia</option>
        <option value="KTM">KTM</option>
        <option value="Lexas">Lexus</option>
        <option value="Mahindra">Mahindra</option>
        <option value="Maruthi">Maruthi</option>
        <option value="Mazda">Mazda</option>
        <option value="Mitsubishi">Mitsubishi</option>
        <option value="Mini">Mini</option>
        <option value="Nissan">Nissan</option>
        <option value="Peugeot">Peugeot</option>
        <option value="Piaggio">Piaggio</option>
        <option value="Royal Enfield">Royal Enfield</option>
        <option value="Subaru">Subaru</option>
        <option value="Suzuki">Suzuki</option>
        <option value="Tata">TaTa</option>
        <option value="Toyata">Toyota</option>
        <option value="Volkswagen">Volkswagen</option>
    </select>